### ISSUE TITLE
can't parse goto

### ISSUE THREAD

**Issue by starius** [andremm/lua-parser#1]
``` lua
lp = require 'lua-parser.parser'
lp.parse('::xx::; goto xxx')
parser.lua:75: bad argument #2 to 'format' (string expected, got nil)
```

**Comment by andremm** [comment]
The problem with your example is that the second parameter of `parse` is missing.
Instead of calling `lp.parse('::xx::; goto xxx')` you should use something like `lp.parse('::xx::; goto xxx', 'goto_test.lua')`.
Note that the first parameter of `parse` is the subject that should be parsed while its second parameter is the subject's name (for instance, the filename being parsed). This name is necessary for error messages.

**Comment by starius** [comment]
I have specified filename:

``` lua
>  lp.parse('::xx::; goto xxx', 'aaa')
_[33] = nil
_[34] = "aaa:1:9: syntax error, no visible label 'xxx' for <goto>"
```

**Comment by andremm** [comment]
Note that your example contains an error: you try to jump to an undefined label (`xxx`). I understand that it is unusual to get a semantic error from a parser, but that is also the way the official Lua parser behaves. If you run your example in the Lua interpreter you will get the following error:
`lua: goto_test.lua:2: no visible label 'xxx' for <goto> at line 1`

**Comment by starius** [comment]
I see. The following code works:

``` lua
lp.parse('::xxx::; goto xxx', '')
```

Thanks!
