### ISSUE TITLE
problem with fix_str() in parser.lua

### ISSUE THREAD

**Issue by bbblitz** [andremm/lua-parser#4]
When given the string
`"\\a"`
The fix_str() function will make this into
`"\\\a"`
Instead of the correct
`"\a"`

This is the same for all escaped characters. (\b,\n,\r ect.)

**Comment by andremm** [comment]
Can you please check whether this issue persists after latest changes?

**Comment by andremm** [comment]
After latest changes, this bug still persists.
In fact, now even the following correct program does not parse:

``` lua
x = "\\"
```

Parsing this program throws the following error message:

``` lua
bug.lua:1:7: syntax error, unclosed string
```

@undecidabot, do you have any thoughts on this?

**Comment by lezgomatt** [comment]
@andremm Hm, I can't seem to reproduce this bug (on latest commit of master). I'm pretty sure this case is already handled by https://github.com/andremm/lua-parser/blob/master/lua-parser/parser.lua#L415.

I could reproduce the exact error message if there's only one backslash as in

```
x = "\"
```

but that wouldn't be a bug then. Are any of the other escape characters also having this issue?

**Comment by andremm** [comment]
> Are any of the other escape characters also having this issue?

@undecidabot, this bug is a bit tricky. :)
And yes, I noticed it with other escape characters (I'm using Lua 5.3.3).

For instance, using the following test file (which I will call `bug1.lua`):

``` lua
local parser = require "lua-parser.parser"
local pp = require "lua-parser.pp"

if #arg ~= 1 then
    print("Usage: parse.lua <string>")
    os.exit(1)
end

local ast, error_msg = parser.parse(arg[1], "example.lua")
if not ast then
    print(error_msg)
    os.exit(1)
end

pp.print(ast)
os.exit(0)
```

Running `$ lua bug1.lua 'x = "\\"'` works, but running `$ lua t.lua "x = '\\'"` does not work.

As another example, using the following test file (which I will call `bug2.lua`):

``` lua
local parser = require "lua-parser.parser"
local pp = require "lua-parser.pp"

local ast, error_msg = parser.parse('x = "\\"', "example.lua")
if not ast then
    print(error_msg)
else
    pp.print(ast)
end

local ast, error_msg = parser.parse("x = '\\'", "example.lua")
if not ast then
    print(error_msg)
else
    pp.print(ast)
end

os.exit(0)
```

Both examples don't work when running `$ lua bug2.lua`.

However, both examples should work, as we can see in the following Lua test:

``` lua
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> x = '\\'
> print(x)
\
> x = "\\"
> print(x)
\
>
```

**Comment by lezgomatt** [comment]
@andremm It took a while, but I've figured it out. There is no bug 😄 

For bug1.lua, `$ lua t.lua "x = '\\'"` fails because the shell escapes characters on double quoted strings, turning the two backslashes into just a single backslash when passed to Lua. 

```
$ echo '\\'
> \\
$ echo "\\"
> \
```

Similarly, for bug2.lua, the characters are being escaped, but this time by Lua. So again, there is only one backslash which is followed by the quote, making the string unclosed just as the error reports. If we change the `\\` into `\\\\`, or use long strings instead, no error will be reported.

This bug was definitely confusing, but I think we can mark it as resolved now 😄

**Comment by andremm** [comment]
> This bug was definitely confusing, but I think we can mark it as resolved now 😄 

You're right @undecidabot. I'm sorry I took too long to reply, but that's great that @bbblitz already closed the issue. Thanks for your feedback!
